# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-10 21:00
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_class', models.CharField(max_length=20)),
                ('stream_id', models.UUIDField(blank=True, null=True)),
                ('seq', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('payload', django.contrib.postgres.fields.hstore.HStoreField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set([('stream_id', 'seq')]),
        ),
        migrations.CreateModel(
            name='TestEventType',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('justeventme.event',),
        ),
    ]
